[package]
name = "sqldb"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
fs4 = "0.12.0"
serde = { version = "1.0.217", features = ["derive"] }
thiserror = "2.0.11"

[dev-dependencies]
tempfile = "3.17.0"
